baseURL = 'https://rimewing.github.io/'
title = 'The Mindweb'
theme = 'risotto'
enableInlineShortcodes = true

# This little bit adds content sections to the main menu.
sectionPagesMenu = "main"

[params.theme]
palette = "modus-tinted"

[params.about]
title = "The Mindweb"
description = "A collection of musings and scripts made by an old runedragon."
logo = "ğŸ‰"

[menu]

[markup]
  [markup.tableOfContents]
    startLevel  = 2
    endLevel    = 3
    ordered     = true

  [markup.goldmark.renderer]
    unsafe      = true

defaultContentLanguage = 'en-us'
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    languageCode = "en-US"
    languageDirection = "ltr"
    languageName = "English"
    weight = 1
