baseURL = 'https://rimewing.github.io/'
languageCode = 'en-us'
title = 'The Mindweb'
theme = 'risotto'
DefaultContentLanguage = 'en-us'
enableInlineShortcodes = true

[params.theme]
palette = "tender"

[params.about]
title = "The Mindweb"
description = "A collection of musings and scripts made by an old runedragon."
logo = "ğŸ‰"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true
